{
    'name': 'Estate',
    'version': '1.0',
    'category': 'Sales',
    'summary': 'Real estate management',
    'description': 'Module for managing real estate properties',
    'author': 'Your Name',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/estate_menuitems.xml',
        'views/estate_type_action.xml',
        'views/estate_type_views.xml',
        'views/estate_tag_action.xml',
        'views/estate_tag_views.xml',
        'views/estate_property_action.xml',
        'views/estate_property_views.xml',
        'views/estate_offer_action.xml',
        'views/estate_offer_views.xml',
        'views/res_users_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
} # type: ignore 